app:
  name: burst
server:
  port: 8888
auth: 
  loginUrl: /login
  secret: c2VkaW4=
  issuer: burst #token签发者
spring: 
  profiles: 
    active: dev
    include: tool #无论何时都讲common包含进来
---

spring: 
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/burst?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
#    password: 123456
  redis:
    host: 172.25.0.15
    port: 6379
    password: 123456
server:
  port: 80
auth: 
  open: false
mybatis-plus: 
  mapper-locations: classpath:/burst/modular/*/mapper/xml/*.xml
  typeAliasesPackage: burst.modular.*.entity
  global-config: 
    cache-enabled: false
    db-column-underline: true
  
---
spring: 
  profiles: test
server: 
  port: 8080
auth: 
  open: true
---
spring: 
  profiles: tool
  devtools: 
    restart:
      enable: false #表示是否触发类修改重启